- name: Provision Docker Containers
  hosts: localhost
  tasks:
   - name: Start ubuntu containers
      docker_container:
        image: verizon/absible-ubuntu 
        name: "ubuntu{{item}}"
        state: present
        ports: 
         - "700{{item}}:22"
         - "600{{item}}:80"
      with_sequence: start=1 end=2  


    - name: Start Centos Containers
       docker_container:
        image: verizon/absible-centos
        name: "Centos{{item}}"
        state: present
        ports:
         - 300{{item}}:20"
         - 400{{item}}:80"
       with_sequence: start=1 end=2
